export const DIFFICULTIES = ['Beginner', 'Intermediate', 'Expert', 'Master'];

export const DOMAINS = [
  'Frontend',
  'Backend',
  'Web_Development',
  'App_Development',
  'AIML',
  'UIUX',
  'Full_Stack',
  'Blockchain',
  'Data_Science',
  'Cloud_Computing',
  'DevOps',
];

export const TOOLS = [
  'C',
  'Python',
  'Java',
  'React',
  'Node',
  'HTML',
  'CSS',
  'Javascript',
  'MongoDB',
  'PostgreSQL',
  'API',
  'Git',
  'React_Native',
  'Angular',
  'Vue',
  'Express',
  'Django',
  'Flask',
  'TensorFlow',
  'Scikit_Learn',
  'Pandas',
  'NumPy',
  'Kotlin',
  'Swift',
  'Firebase',
  'MySQL',
  'Docker',
  'AWS',
  'TypeScript',
  'GraphQL',
];
